Реализована логика авторизации
Sonyamaster1/Pixel-Bros pull request #22
Opened 2023-10-21 11:27 UTC by YaroslavSukhanov

Написан базовый транспорт для наследования, написан транспорт авторизации. 
Настроена обертка роутов для авторизации исходя из логики получение данных юзера с бэка.
Если пользователь неавторзован, он попадает только на роуты, где не требуется авторизация. При попытке зайти на защищенные роуты, его выкинет на страницу логина.
Небольшой рефакторинг

2023-10-21 11:37 UTC, Yrsafam approved these changes

2023-10-22 08:55 UTC, IvanPeleshok commented on packages/client/src/api/base.transport.ts
> +    this.client = axios.create({
Замечательно, что знаете о axios.create

2023-10-22 08:56 UTC, IvanPeleshok commented on packages/client/src/api/sign-in.transport.ts
> +const authURL = 'https://ya-praktikum.tech/api/v2/auth/'
Есть смысл подумать о том, чтобы вынести в переменные окружения

2023-10-22 08:57 UTC, IvanPeleshok commented on packages/client/src/api/sign-in.transport.ts
> +let userData: unknown = {}
Для чего данная переменная?

2023-10-22 08:57 UTC, IvanPeleshok commented on packages/client/src/api/sign-in.transport.ts
> +        console.log(user, 'user')
Нужна ли отладка в деве?

2023-10-22 08:58 UTC, IvanPeleshok commented on packages/client/src/api/sign-in.transport.ts
> +        return (userData = user)
Почему бы просто не вернуть результат резолва промисса?

2023-10-22 08:59 UTC, IvanPeleshok commented on packages/client/src/api/sign-in.transport.ts
> +      .then(user => {
Предлагаю писать код без then / catch, а придерживаться синтаксиса async / await + try / catch
Таким образом, код будет написать в синхронной стилистике, читать и дорабатывать такое намного удобнее

2023-10-22 09:01 UTC, IvanPeleshok commented on packages/client/src/components/change-password-form/change-password-form.component.tsx
> +        placeholder="OLd password"
Old

2023-10-22 09:02 UTC, IvanPeleshok commented on packages/client/src/components/change-password-form/change-password-form.component.tsx
> +        style={{
Почему бы не использовать правила в css?
Инлайн стили сложно перебить в случае необходимости

2023-10-22 09:03 UTC, IvanPeleshok commented on packages/client/src/pages/sign-in-form/sign-in.form.tsx
> +      signInTransport
async / await + try / catch

2023-10-22 09:04 UTC, IvanPeleshok commented on packages/client/src/pages/sign-in-form/sign-in.form.tsx
> +        .then(() => navigate('/game'))
Есть смысл подумать о том, чтобы название роутов вынести в константы (в отдельный модуль)
Так всё будет немного прозрачнее, чище и масштабируемее

2023-10-22 09:07 UTC, IvanPeleshok commented on packages/client/src/router/private-router/index.tsx
> +  return await signInTransport.getUserData()
Обычно разделяют return и await
```
const response = await request()
return response
```

2023-10-22 09:10 UTC, IvanPeleshok commented on packages/client/src/router/private-router/index.tsx
> +const isAuthorized = await getAuthorizedStatus()
Немного странно выглядит

Предлагаю вынести в useEffect и пока идёт запрос - отображать заглушку
После резолва промисса отображать элементы или отправлять на страницу авторизации

2023-10-22 09:13 UTC, IvanPeleshok commented on packages/client/src/components/change-password-form/change-password-form.component.tsx
> +    <Form onSubmit={onSubmit}>
В плане форм предлагаю обратить внимание на `Formik`, очень удобный функционал
Не надо будет писать обёрток вроде handleOnChangeField
https://formik.org/docs/tutorial
В дальнейшем, очень удобно работает с `yup`, с помощью которого удобно валидировать поля
https://www.geeksforgeeks.org/reactjs-form-validation-using-formik-and-yup/

2023-10-22 09:15 UTC, IvanPeleshok requested changes
Проделана большая работа!
Видно, что у вас есть хороший опыт с реактом, нравится
Отлично постарались

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-10-22 12:23 UTC, YaroslavSukhanov commented on packages/client/src/api/sign-in.transport.ts
> +let userData: unknown = {}
Я использую её просто как некую заглушку вместо токена авторизации, пока у нас нет авторизации в этом спринте. Сделал, чтобы приложение уже работало, а авторизация проверялась по типу есть/нет данные юзера у нас в переменной. Если есть, то авторизован, а если нет - не даем попасть на приватные роуты. Для этого приватные роуты обернуты в AuthRout(вроде так называется) и при рендере ребенка внутри этого компонента проверяется, есть ли у нас данные юзера или нет.

2023-10-22 12:24 UTC, YaroslavSukhanov commented on packages/client/src/api/sign-in.transport.ts
> +let userData: unknown = {}
Я её испозую уже в следующей итерации своего кода скорее всего, когда решил доработать функционал

2023-10-22 12:25 UTC, YaroslavSukhanov commented on packages/client/src/api/sign-in.transport.ts
> +        console.log(user, 'user')
Вот именно здесь я в будущем реализовал получения юзера для фейковой авторизации

2023-10-22 12:25 UTC, YaroslavSukhanov commented on packages/client/src/api/sign-in.transport.ts
> +        console.log(user, 'user')
Вот настоящий дев и можно увидеть как это работает - https://github.com/Sonyamaster1/Pixel-Bros/tree/develop

2023-10-22 12:27 UTC, YaroslavSukhanov commented on packages/client/src/api/sign-in.transport.ts
> +        return (userData = user)
Потому что в будущем я для фейковой авторизации проверял наличие данных в переменной userData, она объявлена выше как микростор)
Если просто вернуть, то соответственно при переходе на приватный роут, мы не сможем чекать, есть ли юзер в "сторе" и в таком случае понять, авторизован клиент или нет

2023-10-22 12:28 UTC, YaroslavSukhanov commented on packages/client/src/components/change-password-form/change-password-form.component.tsx
> +        style={{
А это не мой код, я просто вынес компонент отдельно, чтобы было удобнее в будущем им пользоваться.
Это писала @Sonyamaster1, fyi, может поправишь в свободное время

2023-10-22 12:30 UTC, YaroslavSukhanov commented on packages/client/src/router/private-router/index.tsx
> +const isAuthorized = await getAuthorizedStatus()
Да, это просто костыль, но по факту мы это вроде и не должны были делать. Думал сделать заглушку, но решил, что и так начинаю уже в дебри залазить с этой авторизацией, хотя мы все равно ее будем потом переделывать

2023-10-22 12:30 UTC, YaroslavSukhanov commented on packages/client/src/components/change-password-form/change-password-form.component.tsx
> +    <Form onSubmit={onSubmit}>
Тоже код @Sonyamaster1 
fyi

2023-10-22 12:33 UTC, YaroslavSukhanov commented
@IvanPeleshok Привет! Не мог бы подсказать какие конкретно коментарии обязательно нужно поправить для апрува? Просто где-то код немного не мой, где-то кажется нет смысла править, так как я фейкал функционал авторизации, чтобы убого не было до внедрения нормальной авторизации.
Где-то согласен, что это поедет дальше и надо исправить.

2023-10-22 12:38 UTC, YaroslavSukhanov commented on packages/client/src/pages/sign-in-form/sign-in.form.tsx
> +        .then(() => navigate('/game'))
Согласен, но это тоже не моя задача была. Хотел написать отдельный сервис навигации, где создал бы енам с роутами, но понял, что тоже залезаю уже не на свою территорию

2023-10-22 18:01 UTC, IvanPeleshok commented
> @IvanPeleshok Привет! Не мог бы подсказать какие конкретно коментарии обязательно нужно поправить для апрува? Просто где-то код немного не мой, где-то кажется нет смысла править, так как я фейкал функционал авторизации, чтобы убого не было до внедрения нормальной авторизации. Где-то согласен, что это поедет дальше и надо исправить.

@YaroslavSukhanov, поправь то, что считаешь нужным и переводи на код-ревью
Если с чем-то не согласен и мне покажется это важный - обсудим, в остальном без проблем апрувну
На что-то можно ответить просто: в дальнейшем пофиксим / реализуем, есть задачка на эту тему

2023-10-23 07:58 UTC, YaroslavSukhanov commented on packages/client/src/components/change-password-form/change-password-form.component.tsx
> +        placeholder="OLd password"
@Sonyamaster1 fyi
Тоже компонент Сони, скорее всего поправит, если ещё не заметила

2023-10-23 08:10 UTC, YaroslavSukhanov commented
> > @IvanPeleshok Привет! Не мог бы подсказать какие конкретно коментарии обязательно нужно поправить для апрува? Просто где-то код немного не мой, где-то кажется нет смысла править, так как я фейкал функционал авторизации, чтобы убого не было до внедрения нормальной авторизации. Где-то согласен, что это поедет дальше и надо исправить.
> 
> @YaroslavSukhanov, привет Поправь то, что считаешь нужным и переводи на код-ревью Если с чем-то не согласен и мне покажется это важный - обсудим, в остальном без проблем апрувну На что-то можно ответить просто: в дальнейшем пофиксим / реализуем, т.к есть (будет) задачка на эту тему

@IvanPeleshok Привет! Поправил вроде то, что мое. В основном переехал на async/await. Я почему-то думал, что как раз синтаксис с then более модный и современный, а оказалось наоборот)
В остальных комментах постарался отписаться. Если еще что-то посчитаешь нужным, то без проблем поправлю

2023-10-23 16:09 UTC, IvanPeleshok commented
> > > @IvanPeleshok Привет! Не мог бы подсказать какие конкретно коментарии обязательно нужно поправить для апрува? Просто где-то код немного не мой, где-то кажется нет смысла править, так как я фейкал функционал авторизации, чтобы убого не было до внедрения нормальной авторизации. Где-то согласен, что это поедет дальше и надо исправить.
> > 
> > 
> > @YaroslavSukhanov, привет Поправь то, что считаешь нужным и переводи на код-ревью Если с чем-то не согласен и мне покажется это важный - обсудим, в остальном без проблем апрувну На что-то можно ответить просто: в дальнейшем пофиксим / реализуем, т.к есть (будет) задачка на эту тему
> 
> @IvanPeleshok Привет! Поправил вроде то, что мое. В основном переехал на async/await. Я почему-то думал, что как раз синтаксис с then более модный и современный, а оказалось наоборот) В остальных комментах постарался отписаться. Если еще что-то посчитаешь нужным, то без проблем поправлю

@YaroslavSukhanov, привет
Переведи пожалуйста таску на ревью, возьму в работу по проверке

2023-10-24 08:00 UTC, YaroslavSukhanov commented
> > > > @IvanPeleshok Привет! Не мог бы подсказать какие конкретно коментарии обязательно нужно поправить для апрува? Просто где-то код немного не мой, где-то кажется нет смысла править, так как я фейкал функционал авторизации, чтобы убого не было до внедрения нормальной авторизации. Где-то согласен, что это поедет дальше и надо исправить.
> > > 
> > > 
> > > @YaroslavSukhanov, привет Поправь то, что считаешь нужным и переводи на код-ревью Если с чем-то не согласен и мне покажется это важный - обсудим, в остальном без проблем апрувну На что-то можно ответить просто: в дальнейшем пофиксим / реализуем, т.к есть (будет) задачка на эту тему
> > 
> > 
> > @IvanPeleshok Привет! Поправил вроде то, что мое. В основном переехал на async/await. Я почему-то думал, что как раз синтаксис с then более модный и современный, а оказалось наоборот) В остальных комментах постарался отписаться. Если еще что-то посчитаешь нужным, то без проблем поправлю
> 
> @YaroslavSukhanov, привет Переведи пожалуйста таску на ревью, возьму в работу по проверке

@IvanPeleshok Привет! Готово, надеюсь правильно все сделал. На доске перетащил в Review: Praktikum. На всякий случай - https://linear.app/pixel-bros/issue/PIX-16/7-realizovat-logiku-avtorizacii

2023-10-24 13:21 UTC, IvanPeleshok commented
> > > > > @IvanPeleshok Привет! Не мог бы подсказать какие конкретно коментарии обязательно нужно поправить для апрува? Просто где-то код немного не мой, где-то кажется нет смысла править, так как я фейкал функционал авторизации, чтобы убого не было до внедрения нормальной авторизации. Где-то согласен, что это поедет дальше и надо исправить.
> > > > 
> > > > 
> > > > @YaroslavSukhanov, привет Поправь то, что считаешь нужным и переводи на код-ревью Если с чем-то не согласен и мне покажется это важный - обсудим, в остальном без проблем апрувну На что-то можно ответить просто: в дальнейшем пофиксим / реализуем, т.к есть (будет) задачка на эту тему
> > > 
> > > 
> > > @IvanPeleshok Привет! Поправил вроде то, что мое. В основном переехал на async/await. Я почему-то думал, что как раз синтаксис с then более модный и современный, а оказалось наоборот) В остальных комментах постарался отписаться. Если еще что-то посчитаешь нужным, то без проблем поправлю
> > 
> > 
> > @YaroslavSukhanov, привет Переведи пожалуйста таску на ревью, возьму в работу по проверке
> 
> @IvanPeleshok Привет! Готово, надеюсь правильно все сделал. На доске перетащил в Review: Praktikum. На всякий случай - https://linear.app/pixel-bros/issue/PIX-16/7-realizovat-logiku-avtorizacii

@YaroslavSukhanov, привет!
Работа всё ещё на твоей стороне в таск-трекере яндекс практикума
Уточни пожалуйста у команды или ментора, как перевести работу на повторное ревью

2023-10-26 17:14 UTC, IvanPeleshok approved these changes
Всё гуд!

Поздравляю, работа принята!
Обратите внимание ваших коллег о замечаниях, на которые я указал

Хорошего дня :)

2023-10-30 09:18 UTC, closed without merging