game engaine
Sonyamaster1/Pixel-Bros pull request #23
Opened 2023-10-21 11:45 UTC by J4rCen

### Какую задачу решаем
Задача PIX-26
Создание игрового движка
https://linear.app/pixel-bros/issue/PIX-26/17-sozdat-mehaniku-igry-na-canvas-api

### Скриншоты/видяшка (если есть)

![image](https://github.com/Sonyamaster1/Pixel-Bros/assets/63585689/293ed768-a521-4262-aed3-99ddd5471f06)

2023-10-22 07:18 UTC, Yrsafam approved these changes

2023-10-22 14:48 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду.
Написал комментарии

2023-10-22 14:48 UTC, Olegas commented on packages/client/src/components/game_engaine/Bird.ts
> +    }
Зачем объявлять методы в конструкторе? Их можно объявить сразу при описании класса (вместо "пустышек" которые написаны сейчас в объявлении класса) а в конструкторе только проинициализировать свойства

2023-10-22 14:48 UTC, Olegas commented on packages/client/src/components/game_engaine/Bird.ts
> +        (this.image = Sprites.birdImg),
Это присвоение нужно написать в определении свойства

2023-10-22 14:48 UTC, Olegas commented on packages/client/src/components/game_engaine/Pipes.ts
> +  draw: () => void
Аналогичное замечание как и в классе Bird

2023-10-22 14:48 UTC, Olegas commented on packages/client/src/components/game_engaine/Bird.ts
> +      ctx.translate(this.x, this.y)
Если методы описываются тут только ради доступа к ctx - объяви его как свойство, проинициализируй в конструкторе и дальше можно получать доступ через this

2023-10-22 14:48 UTC, Olegas commented on packages/client/src/components/game_engaine/Pipes.ts
> +        (this.image = Sprites.pipeUpImg),
Зачем тут присваивать постоянно свойство image? Почему сразу не использовать просто элемент из Sprites? Тут image вообще не нужен как свойство класса

2023-10-22 14:48 UTC, Olegas commented on packages/client/src/components/game_engaine/Word.ts
> +    }
Те же замечания что и в классе Bird

2023-10-22 14:48 UTC, Olegas commented on packages/client/src/components/game_engaine/GameEngaine.tsx
> +      requestAnimationFrame(animate)
Нет никакого механизма остановки анимации. Как минимум у вас есть game over а еще есть разрушение компонента (когда пользователь перешел на другую страницу). В этих ситуациях надо останавливать игру и анимацию

2023-10-23 19:59 UTC, Olegas approved these changes
Работа принята

2023-10-30 09:41 UTC, merged