Создана страница Leaderboard,
Sonyamaster1/Pixel-Bros pull request #27
Opened 2023-10-26 17:51 UTC by daikoziyevBaha

### Какую задачу решаем
PIX-20 Сверстать страницу лидерборд
https://linear.app/pixel-bros/issue/PIX-20/11-sverstat-stranicu-liderbord

### Скриншоты/видяшка (если есть)
<img width="1430" alt="Снимок экрана 2023-10-26 в 23 50 04" src="https://github.com/Sonyamaster1/Pixel-Bros/assets/99397710/9f32c340-abb3-4517-b82b-1df3f9095529">

2023-10-27 13:51 UTC, YaroslavSukhanov requested changes

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +            items.map(item => (
На мой взгляд намного лучше создать отдельный компонент LeaderBordCell, например. Там принимать в пропсы имя и кол-во поинтов. Тогда нужно будет мапить уже в этот компонент и прокидывать данные в пропсы. 
У тебя получится что-то вроде `players.map(player => <LeaderBordCell score={player.score} score={player.name} />`
Так мы забираем у пользователя доступ к кишкам этого компонента и даём ему только интерфейс.

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +    <div className={styles.leaderboard}>
Это я бы тоже вынес в один компонент-декоратор, который бы назывался <LeaderBoardContainer>, который в детей принимал бы уже контент в виде ячеек с данными игроков. 

Получится 
```
<LeaderBoardContainer>
  {players.map(player => <LeaderBordCell score={player.score} score={player.name} />}
</LeaderBoardContainer>;
```

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +        <h1 className={styles.content__title}>Leaderboard</h1>
Насколько я помню, я в компонентах делал компонент EntityHeader. Кажется, он должен почти идеально подойти в этом случае

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +          className={styles.go_back_btn}
На мой взгляд прокидывать пропсами стили в существующий атомарный компонент нужно лишь в том случае, если они применяются динамически и то лучше вытащить условно стейт наружу и туглить его через пропсы.
На твоем месте я бы просто подумал почему кнопка у тебя не встает и уже внутри нее немного поправить стили, убедившись, что у остальных пользователей она не уехала. Если это кардинально другое состояние, то уже тогда просто вытаскивать пропс. Но у тебя кажется достаточно стандартный кейс. Я думаю, если ты создашь контейнер для своего компонента, то в нем и можно будет откалибровать расположение компонентов внутри, без изменения стилей в самой кнопке.

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +          {items.length > 0 &&
По идее нет необходимости проверять длину массива, ибо достаточно проверить, не возвращает ли фолси значение твоя переменная, например `!!items`

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +const fakeResults = [
На мой взгляд бизнес-данные не должны хранится в компоненте и я бы вынес их в константу FAKE_RESULTS. Да, вижу, что это просто заглушка)

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.module.scss
> +.leaderboard {
Считаю, что не лучшая практика засовывать стили для разных компонентов в один индекс. Я бы вынес это по разным scss файлам, в таком случае и путь импорта в других компонентах у тебя будет самодокументированным и будет понятно что за стиль и откуда мы используем

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/fetchers.ts
> +const getAllLeaderboard = async () => {
на мой взгляд луче создать отдельный транспорт для лидерборда, который будет расширять базовый класс транспорта, потому что там уже есть всё необходимое апи, а он ждет от тебя только эндпоинт и полезную нагрузку, если она существует. Так будет прозе дебажить в будущем и ловить данные по цепочке, если запрос будет работать некорректно.

2023-10-27 13:51 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +        {error && <p className={styles.error}>{error}</p>}
А у нас в лидрборде могут быть какие-то ошибки? Я думал, что это тупо ридонли компонент, который отображает рейтинг

2023-11-02 16:00 UTC, daikoziyevBaha commented on packages/client/src/pages/leaderboard/index.tsx
> +          className={styles.go_back_btn}
Я расширил компонент FooterButton, с возможностью добавлять дополнительные классы в отдельных случаях, по дефолту подставляется стандартный класс + "", так же лишняя обертку из div думаю не совсем уместна

2023-11-02 16:02 UTC, daikoziyevBaha commented on packages/client/src/pages/leaderboard/index.tsx
> +        {error && <p className={styles.error}>{error}</p>}
В случае ошибок от 400-415

2023-11-02 16:03 UTC, daikoziyevBaha commented on packages/client/src/pages/leaderboard/fetchers.ts
> +const getAllLeaderboard = async () => {
Это можно сделать, я думаю прописывать лишний код и создавать класс, когда в лидерборде всего 1 get api немного излишне

2023-11-03 09:42 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +          className={styles.go_back_btn}
У тебя уже есть эта обёртка `<div className={styles.leaderboard}>`

2023-11-03 09:43 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/index.tsx
> +        {error && <p className={styles.error}>{error}</p>}
Я думал, что у нас для них отдельные экраны, а у тебя просто ошибка встанет посередине, у тебя ведь не условный рендер

2023-11-03 09:43 UTC, YaroslavSukhanov commented on packages/client/src/pages/leaderboard/fetchers.ts
> +const getAllLeaderboard = async () => {
Да, но в таком случае у нас получается "для учебного проекта ок", а не учимся делать расширяемое приложение

2023-11-03 09:43 UTC, YaroslavSukhanov approved these changes

2023-11-03 09:59 UTC, merged