Feature
Sonyamaster1/Pixel-Bros pull request #30
Opened 2023-10-31 12:18 UTC by Yrsafam

### Какую задачу решаем
Реализация web api.

![изображение](https://github.com/Sonyamaster1/Pixel-Bros/assets/60210785/e485ebf7-f9f5-4522-9981-9115ead6cd4a)

Задача: PIX-33

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2023-11-03 12:16 UTC, YaroslavSukhanov approved these changes

2023-11-03 12:16 UTC, YaroslavSukhanov commented on packages/client/src/hooks/useFullscreen.ts
> +    } else if (document.exitFullscreen) {
Здесь не подойдёт так?

```
else if (event.code === keyCodeClose && document.exitFullscreen) {
    document.exitFullscreen();
  }
```

2023-11-03 12:16 UTC, YaroslavSukhanov commented on packages/client/src/hooks/useFullscreen.ts
> +export function useFullscreen<T extends HTMLElement>(
Почему решил наименовать как хук? Кажется, у тебя это просто функция, а не хук

2023-11-03 12:16 UTC, YaroslavSukhanov commented on packages/client/src/hooks/useFullscreen.ts
> +    if (!document.fullscreenElement) {
Мне кажется, или у тебя здесь проверка будет на каждую любую нажатую влавишу? Кажется, правильнее будет сначала валидировать, что сработала одна из клавиш,  которые мы хотим обрабатывать и уже потом смотреть как именно мы должны реагировать на нажатие в зависимости от клавиши. Но я может плохо погружен в контекст

2023-11-03 18:25 UTC, Yrsafam commented on packages/client/src/hooks/useFullscreen.ts
> +export function useFullscreen<T extends HTMLElement>(
Внутри используется useEffect же

2023-11-04 10:53 UTC, YaroslavSukhanov commented on packages/client/src/hooks/useFullscreen.ts
> +export function useFullscreen<T extends HTMLElement>(
Ты прав, мне показалось, что useEffect снаружи функции, а сейчас нормально присмотрелся и вижу, что он внутри

2023-11-04 15:38 UTC, IvanPeleshok commented on packages/client/src/hooks/useFullscreen.ts
> +      refFullscreenContainer.current?.requestFullscreen()
requestFullscreen не во всех браузерах поддерживается: https://caniuse.com/?search=requestFullscreen

Для совместимости с остальными браузерами выглядело бы как-то так: https://stackoverflow.com/questions/13503016/how-to-enable-ie-full-screen-feature-like-firefox-and-chrome#:~:text=sheelpriy%20answer%20is%20good%20with%20a%20small%20change%2C%20successfully%20tested%20on%20chrome%2C%20firefox%2C%20ie%2C%20safari%20and%20opera%20(all%20last%20version)

(Для ознакомления)

2023-11-04 15:39 UTC, IvanPeleshok requested changes
Замечательная работа!
Здорово постарались!
Круто, что вынесли в кастомный хук

Поздравляю, апрув
Хорошего дня :)

2023-11-05 03:44 UTC, merged