В проект добавлены redux-toolkit и react-redux, создан store с одним …
Sonyamaster1/Pixel-Bros pull request #33
Opened 2023-11-03 04:33 UTC by daikoziyevBaha

Добавлен redux-toolkit, authSlice, hook useAuth.

2023-11-04 09:59 UTC, Yrsafam approved these changes

2023-11-04 12:59 UTC, YaroslavSukhanov approved these changes

2023-11-04 12:59 UTC, YaroslavSukhanov commented on packages/client/src/store/slices/userSlices.ts
> +    setUser(state, action) {
Здесь можно сделать немого проще, используя спред оператор
```
setUser(state, action) {
      return { ...state, ...action.payload };
    },
```

2023-11-04 12:59 UTC, YaroslavSukhanov commented on packages/client/src/store/slices/userSlices.ts
> +    removeUser(state) {
Судя по тому, что ты каждому полю присваиваешь null, тебе нужно просто привести состояние к initialState

Ты можешь просто сделать     
```
removeUser(state) {
      return { ...initialState };
    },
```

2023-11-04 12:59 UTC, YaroslavSukhanov commented on packages/client/src/store/slices/userSlices.ts
> +const initialState = {
Я бы всё же добавил типизацию. У тебя расширение файла .ts, однако не прописан даже тип для модельки юзера, а он для нас ключевое значение имеет.

2023-11-05 15:16 UTC, IvanPeleshok commented on packages/client/src/App.tsx
> +    signInTransport.getUserData().then(user => {
Предлагаю использовать thank-и - предпочтительное использование работы с апи в интеграции с редакс
https://redux-toolkit.js.org/api/createAsyncThunk

2023-11-05 15:17 UTC, IvanPeleshok commented on packages/client/src/App.tsx
> +    signInTransport.getUserData().then(user => {
Предлагаю переписать все асинхронные запросы на async / await + try / catch - код читается в таком случае лучше

2023-11-05 15:19 UTC, IvanPeleshok commented on packages/client/src/store/slices/userSlices.ts
> +    setUser(state, action) {
Предлагаю затипизировать редьюсеры

2023-11-05 15:22 UTC, IvanPeleshok commented on packages/client/src/store/slices/userSlices.ts
> +      return { ...state, ...action.payload }
В redux-toolkit можно мутировать state напрямую при обращению к полю объекта state
Пример
```
reducer(
        state,
        action: PayloadAction<Page[], string, { currentPage: number }>
      ) {
        state.all = action.payload
        state.meta = action.meta
      },
```

2023-11-05 15:24 UTC, IvanPeleshok requested changes
Отличная работа!
Здорово постарались!

Есть небольшие замечания, предлагаю доработать

Хорошего дня :)

2023-11-09 18:26 UTC, IvanPeleshok approved these changes
Отлично потрудились!

Поздравляю, работа принята!

Хорошего дня :)

2023-11-10 05:27 UTC, merged