Pix 31 service worker
Sonyamaster1/Pixel-Bros pull request #34
Opened 2023-11-03 14:53 UTC by YaroslavSukhanov

Теперь пользователь может играть в игру и посещать основные экраны игры оффлайн

2023-11-04 10:14 UTC, Yrsafam approved these changes

2023-11-04 19:15 UTC, Olegas commented on packages/client/service.worker.js
> +]
Данный подход не будет работать на production-сборке. Для prod-сборки с такой настройкой service worker не сможет ничего закэшировать, потому что таких файлов нет (в prod-режиме)

2023-11-04 19:17 UTC, Olegas requested changes
Добрый день.
В данной реализации есть проблема - указал продробности в отдельном комментарии.
Нужно либо написать решение, которое будет работать и на production или отказаться от предварительного кэширования совсем.

2023-11-05 07:50 UTC, YaroslavSukhanov commented on packages/client/service.worker.js
> +]
Добрый день!
К сожалению, ревью по типу "это не будет работать" мне не очень помогает в исправлении замечаний. 
Насколько я понимаю, при ревью проверяющий подсказывает решение или даёт ссылки на материалы, из которых можно узнать как это замечание исправить. Ни то, ни другое не было сделано.
Специально прочитал принципы проведения код-ревью и почти все из них были просто проигнорированы, кроме того, что стоит указать на ошибку.
Я написал свой код очень близко к тому, как обучает теория, однако конечно могут допустить ошибки и понимаю, что где-то допустил их. И 
Также вы сказали, что один из вариантов - это вообще отказаться от предварительного кэширования. Для меня это звучит как отказаться от использования сервис воркеров, хотя именно в этом и была основная задача этого кода. Что имелось в виду?

2023-11-06 05:42 UTC, Olegas commented on packages/client/service.worker.js
> +]
Я предпочитаю дать возможность самостоятельно разобраться в проблеме прежде чем давать готовые решения ;)
Начну с последнего момента: SW можно использовать для случая, когда приложение сперва загрузилось нормально (в этом случае у тебя загрузится приложение и все запросы попадут в кэш, но это произойдет по мере использования) а затем, при пропаже связи, мы могли брать данные из кэша (но только те, которые ранее были запрошены). Этот вариант конечно похуже варианта с предзагрузкой, но тоже рабочий.
По способу реализации предзагрузки:
1. Можно использовать Vite-PWA и механизм injectManifest https://vite-pwa-org.netlify.app/workbox/inject-manifest.html с помощью которого service worker будет знать о всех файлах, которые есть в приложении
2. (более сложный) Можно написать свой плагин для Vite который сохранит при сборке данные о файлах внутрь файла service worker'а

2023-11-06 06:46 UTC, YaroslavSukhanov commented on packages/client/service.worker.js
> +]
Я не понимаю как связано "подсказать решение" и дать ссылку на материал, с "давать готовое решение". Я просил разве давать мне готовое решение или вы сами это придумали и использовали как аргумент, чтобы оправдать тот факт, что провели ревью по типу "это не работает"? Я понимаю, что у вас есть ваше "я предпочитаю", однако у меня есть дедлайн и желание обучиться. Я предпочитаю получать услуги качественные и ревью в том виде, в котором оно может помочь студенту, а не просто узнать тот факт, что "это не работает".
Со всем уважением.

2023-11-06 06:49 UTC, YaroslavSukhanov commented on packages/client/service.worker.js
> +]
Также вы сказали "Начну с последнего момента" и написали своё предложение. Спасибо большое.
Сможете подсказать не с последним моментом? Я про пути к файлам, которых не будет про сборке в проде. Как я понял, явно проблема с путями и они должны быть другими.

2023-11-06 08:20 UTC, Olegas commented on packages/client/service.worker.js
> +]
Да, верно, проблема с путями. Они не то что другие, они на каждую сборку разные.  

Я написал способ решения, см выше со слов « По способу реализации предзагрузки:»

2023-11-06 14:10 UTC, YaroslavSukhanov commented on packages/client/service.worker.js
> +]
Спасибо
Для чистоты совести и прозрачности напишу, что мне непонятно что мне нужно делать

2023-11-07 14:44 UTC, YaroslavSukhanov commented
Привет!
Кажется, я сделал предзагрузку теперь правильно, но не факт, что правильно и что это вообще будет работать)
Если я что-то неправильно сделал или не доделал, то дай знать, пожалуйста

2023-11-07 16:44 UTC, Olegas commented
@YaroslavSukhanov ты пошел в правильно направлении, но у тебя теперь получилось как бы две предзагрузки. Одна твоя старая, другая новая, которая берет данные из __WB_MANIFEST.
Что надо сделать:
1. Сама предазгрузка у тебя уже написана вот тут https://github.com/Sonyamaster1/Pixel-Bros/pull/34/files#diff-e7ddb74fdf269e6fc426022cdbed854e8443adc3d14586af99aab51bdefd2dcdR19 Единственное что в ней те так - неправильный список адресов для загрузки
2. Собери приложение для продакшена и посмотри отладчиком в файл service worker (поставь точку останова в начале файла и остановись там в момент установки sw) - ты увидишь что конструкцию self.__WB_MANIFEST сборщик заменил на массив объектов (или строк, я не помню наизусть, но ты отладчиком все увидишь) и в этих лбъектах есть пути доя собранных файлов
3. Возьми эти пути и запусти твой код предзагрузки (из п.1) по этому массиву путей.
И будет отличное решение.

2023-11-08 08:37 UTC, YaroslavSukhanov commented
> @YaroslavSukhanov ты пошел в правильно направлении, но у тебя теперь получилось как бы две предзагрузки. Одна твоя старая, другая новая, которая берет данные из __WB_MANIFEST. Что надо сделать:
> 
> 1. Сама предазгрузка у тебя уже написана вот тут https://github.com/Sonyamaster1/Pixel-Bros/pull/34/files#diff-e7ddb74fdf269e6fc426022cdbed854e8443adc3d14586af99aab51bdefd2dcdR19 Единственное что в ней те так - неправильный список адресов для загрузки
> 2. Собери приложение для продакшена и посмотри отладчиком в файл service worker (поставь точку останова в начале файла и остановись там в момент установки sw) - ты увидишь что конструкцию self.__WB_MANIFEST сборщик заменил на массив объектов (или строк, я не помню наизусть, но ты отладчиком все увидишь) и в этих объектах есть пути для собранных файлов
> 3. Возьми эти пути и запусти твой код предзагрузки (из п.1) по этому массиву путей.
>    И будет отличное решение.

@Olegas  Привет!
Я попробовал сделать то, как ты написал, но у меня не получилось.
Я не знаю как правильно дебажить на сборке для прода, а в собранном файле сервис воркера пути я не нашел. Дебаггер падал в других случаях, потому что не находил self, если я дебажил конкретно файл сервис воркера. В общем мои попытки можно описать на тысячу знаков и это утомит) В итоге я запустил сборку для прода и посмотрел сервис воркер, который создалась с помощью плагина и там были пути, их я взял оттуда и заменил свои. Но мне кажется, что так работать не должно, они ведь скорее всего новые создаются.

2023-11-08 17:05 UTC, Olegas commented
@YaroslavSukhanov https://github.com/Sonyamaster1/Pixel-Bros/pull/37/files вот так будет работать

2023-11-08 17:06 UTC, Olegas commented
@YaroslavSukhanov 
<img width="742" alt="Снимок экрана 2023-11-08 в 20 05 43" src="https://github.com/Sonyamaster1/Pixel-Bros/assets/389390/6ac81be3-4af7-4100-99e4-96c48bf59df7">
<img width="629" alt="Снимок экрана 2023-11-08 в 20 06 19" src="https://github.com/Sonyamaster1/Pixel-Bros/assets/389390/31970c94-f148-4fbf-bb81-ca367cedff11">

2023-11-09 10:57 UTC, YaroslavSukhanov commented
> @YaroslavSukhanov https://github.com/Sonyamaster1/Pixel-Bros/pull/37/files вот так будет работать

Вот что ты имел в виду, когда говорил, что у меня дважды есть предварительное кэширование. Получается, что и не нужно было мне использовать precacheAndRoute. 
Спасибо, что помог. Мне явно надо научиться дебажить сборку и ещё подразобраться в работе сервис воркеров.
Твою строку добавил, спасибо тебе за терпение

2023-11-09 13:09 UTC, merged