PIX-40: добавила апи
Sonyamaster1/Pixel-Bros pull request #39
Opened 2023-11-20 13:19 UTC by Sonyamaster1

### Какую задачу решаем
Добавить новое API - API шуток и фраз Чака Нирриса
### Скриншоты/видяшка (если есть)
<img width="845" alt="image" src="https://github.com/Sonyamaster1/Pixel-Bros/assets/104299667/daed0358-918a-4f4a-a61a-96078c1f48d6">

### TBD (если есть)

2023-11-20 13:29 UTC, Sonyamaster1 commented
Никак не могу найти открытое апи перевода, поэтому текст остался на оригинальном языке. Да и идей для нового апи - маловато

2023-11-20 18:36 UTC, IvanPeleshok requested changes
Проделана большая работа!
Отлично потрудились!

Есть замечания, предлагаю доработать

Обязательно покажите работу своей команде, нужен минимум один апрув от вашей команды

Хорошего дня :)

2023-11-20 18:36 UTC, IvanPeleshok commented on packages/client/src/api/jokes.transport.ts
> +        console.log(user, 'joke')
Для какой цели необходима отладка в деве?

2023-11-20 18:36 UTC, IvanPeleshok commented on packages/client/src/api/jokes.transport.ts
> +let userData: unknown = {}
Предлагаю указать тип для ответа от сервера

2023-11-20 18:36 UTC, IvanPeleshok commented on packages/client/src/api/jokes.transport.ts
> +        return (userData = user)
Достаточно странная конструкция

Для какой цели это необходимо?

2023-11-20 18:36 UTC, IvanPeleshok commented on packages/client/src/pages/home/index.tsx
> +              jokesTransport.getRandomJoke().then((res: any) => {
Предлагаю вынести в функцию, обьявленную в теле компоненты

Для обработки использовать async / await + try / catch

```
const getJoke = async () => {
  try {
    const response = jokesTransport.getRandomJoke()
    setJoke(response.value)
  } catch (error) {}
}

return (
  <button onClick={getJoke} />
```

Никаких any в проекте не должно быть, теряется смысл использования ts

В идеале должна быть дополнительная прослойка работы с апи
Как пример, санки из redux-thunk
Есть в планах его внедрить?

2023-11-23 08:59 UTC, YaroslavSukhanov requested changes

2023-11-23 08:59 UTC, YaroslavSukhanov commented on packages/client/src/api/jokes.transport.ts
> +        console.log(joke, 'joke')
Предлагаю выпилить логирование, иначе будет стрелять в будущем всем твои логи и придется искать и удалять

2023-11-23 08:59 UTC, YaroslavSukhanov commented on packages/client/src/api/jokes.transport.ts
> +  getRandomJoke() {
Предлагаю всё же добавить типизацию. Методы базового класса умеют принимать дженерики и так мы застрахуем себя еще на этапе разработки от ситуации, когда у кого-то будет что-то негарантированно прокидываться и твой транспорт начнет ругаться

2023-11-23 08:59 UTC, YaroslavSukhanov commented on packages/client/src/pages/home/index.tsx
> +      jokesTransport.getRandomJoke().then((res: any) => {
Здесь бы тоже убрать any, когда типизируешь метод своего транспорта. + стейт можно будет тоже типизировать через модель, которая возвращается с бэка

2023-11-23 12:27 UTC, YaroslavSukhanov approved these changes
Апрув!

2023-11-23 21:33 UTC, IvanPeleshok commented on packages/client/src/pages/home/index.tsx
> +      jokesTransport.getRandomJoke().then((res: IJoke) => {
Когда используем async / await нет необходимости в колбеке then или catch
Используйте конструкцию до конца:
```
const response = jokesTransport.getRandomJoke()
setJoke(response.value)
```

Ранее оставлял пример: https://github.com/Sonyamaster1/Pixel-Bros/pull/39#discussion_r1399598310

2023-11-23 21:34 UTC, IvanPeleshok approved these changes
Проделана большая работа!
Отлично потрудились!

Работа не имеет критических замечания
Поздравляю, апрув 🚀 

Оставил комментарии по улучшению реализации фичи

Хорошего дня :)

2023-11-25 09:03 UTC, merged